### PR TITLE
Use substring instead of replace()

### PR DESCRIPTION
**Pull request by tjvr**
Hi! This is a very silly question, so feel free to ignore.

I'm just curious why you don't use substring; wouldn't [that be faster](https://jsperf.com/substr-vs-substring-vs-replace)? Since replace() has to compare the characters again. :)

### CODE REVIEW

**Comment by tandrewnichols** [comment]
I wasn't really concerned with performance, as I was writing this for a personal project that didn't require it (i.e. not for a lexer or tokenizer or anything). Nor for that matter am I really up to speed on jsperf stuff. But if you get the tests passing, I'm not opposed to merging it.

**Comment by tjvr** [comment]
That's good to know. Thanks for your time :-)

**Comment by tandrewnichols** [comment]
So . . . not interested? Seems like it shouldn't be hard to fix the tests. I didn't run them to see why they were failing and the messages in travis were not super helpful: return value was false or something.

**Comment by tandrewnichols** [comment]
I made this change and published it in v1.0.7. Thanks for opening the issue!

**Comment by tjvr** [comment]
:)

**Pull request closed without merging**
